#define CG_KEY_BACKSPACE                        0x08
#define CG_KEY_TAB                              0x09
#define CG_KEY_ENTER                            0x0D
#define CG_KEY_NUMPAD_PLUS                      0x6B
#define CG_KEY_NUMPAD_MINUS                     0x6D
#define CG_KEY_NUMPAD_PERIOD                    0x6E
#define CG_KEY_NUMPAD_SLASH                     0x6F
#define CG_KEY_ESCAPE                           0x1B
#define CG_KEY_0                                0x30
#define CG_KEY_1                                0x31
#define CG_KEY_2                                0x32
#define CG_KEY_3                                0x33
#define CG_KEY_4                                0x34
#define CG_KEY_5                                0x35
#define CG_KEY_6                                0x36
#define CG_KEY_7                                0x37
#define CG_KEY_8                                0x38
#define CG_KEY_9                                0x39
#define CG_KEY_A                                0x41
#define CG_KEY_B                                0x42
#define CG_KEY_C                                0x43
#define CG_KEY_D                                0x44
#define CG_KEY_E                                0x45
#define CG_KEY_F                                0x46
#define CG_KEY_G                                0x47
#define CG_KEY_H                                0x48
#define CG_KEY_I                                0x49
#define CG_KEY_J                                0x4A
#define CG_KEY_K                                0x4B
#define CG_KEY_L                                0x4C
#define CG_KEY_M                                0x4D
#define CG_KEY_N                                0x4E
#define CG_KEY_O                                0x4F
#define CG_KEY_P                                0x50
#define CG_KEY_Q                                0x51
#define CG_KEY_R                                0x52
#define CG_KEY_S                                0x53
#define CG_KEY_T                                0x54
#define CG_KEY_U                                0x55
#define CG_KEY_V                                0x56
#define CG_KEY_W                                0x57
#define CG_KEY_X                                0x58
#define CG_KEY_Y                                0x59
#define CG_KEY_Z                                0x5A
#define CG_KEY_NUMPAD_ASTERISK                  0x6A
#define CG_KEY_NUMPAD_0                         0x60
#define CG_KEY_NUMPAD_1                         0x61
#define CG_KEY_NUMPAD_2                         0x62
#define CG_KEY_NUMPAD_3                         0x63
#define CG_KEY_NUMPAD_4                         0x64
#define CG_KEY_NUMPAD_5                         0x65
#define CG_KEY_NUMPAD_6                         0x66
#define CG_KEY_NUMPAD_7                         0x67
#define CG_KEY_NUMPAD_8                         0x68
#define CG_KEY_NUMPAD_9                         0x69
#define CG_KEY_COLON_SEMICOLON                  0xBA
#define CG_KEY_QUEST_MARK_SLASH                 0xBF
#define CG_KEY_TILDE                            0xC0
#define CG_KEY_LEFT_SQUARE_CURLY_BRACKET        0xDB
#define CG_KEY_RIGHT_SQUARE_CURLY_BRACKET       0xDD
#define CG_KEY_VERTICAL_BAR_BACKSLASH           0xDC
#define CG_KEY_QUOT_MARK_APOSTROPHE             0xDE
#define CG_KEY_LESS_COMMA                       0xBC
#define CG_KEY_GREATER_PERIOD                   0xBE
#define CG_KEY_MINUS_LOWBAR                     0xBD
#define CG_KEY_PLUS_EQUAL                       0xBB
#define CG_KEY_SPACEBAR                         0x20
#define CG_KEY_CAPS_LOCK                        0x14
#define CG_KEY_DELETE                           0x2E
#define CG_KEY_DOWN                             0x28
#define CG_KEY_END                              0x23
#define CG_KEY_F1                               0x70
#define CG_KEY_F2                               0x71
#define CG_KEY_F3                               0x72
#define CG_KEY_F4                               0x73
#define CG_KEY_F5                               0x74
#define CG_KEY_F6                               0x75
#define CG_KEY_F7                               0x76
#define CG_KEY_F8                               0x77
#define CG_KEY_F9                               0x78
#define CG_KEY_F10                              0x79
#define CG_KEY_F11                              0x7A
#define CG_KEY_F12                              0x7B
#define CG_KEY_HOME                             0x24
#define CG_KEY_INSERT                           0x2D
#define CG_KEY_LEFT_CONTROL                     0xA2
#define CG_KEY_LEFT                             0x25
#define CG_KEY_LEFT_ALT                         0xA4
#define CG_KEY_LEFT_SHIFT                       0xA0
#define CG_KEY_LEFT_WINDOWS                     0x5B
#define CG_KEY_PAGE_DOWN                        0x22
#define CG_KEY_NUM_LOCK                         0x90
#define CG_KEY_PAGE_UP                          0x21
#define CG_KEY_RIGHT_CONTROL                    0xA3
#define CG_KEY_RIGHT_ALT                        0xA5
#define CG_KEY_RIGHT                            0x27
#define CG_KEY_RIGHT_SHIFT                      0xA1
#define CG_KEY_RIGHT_WINDOWS                    0x5C
#define CG_KEY_SCROLL_LOCK                      0x91
#define CG_KEY_PRINT_SCREEN                     0x2C
#define CG_KEY_UP                               0x26
